version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event
    volumes:
      - ./data:/data/postgres
    ports:
      - "5432:5432"
